### ISSUE TITLE
PostTech username and password

### ISSUE THREAD

**Issue by pipks** [Popinek/postTechBot#1]
We login to post.tech via Twitter. Where can we get password and password information?

**Comment by Popinek** [comment]
create .env file like it says in Getting Started:
Set up your environment variables by creating a .env file in the project directory with the following content:
username=user1
password=pass
gpt=apikey

user1 is your twitter handle and pass is your twitter password, you can create twitter accounts yourself (this tool doesnt create twitter account and also doesnt work if you still didnt create your post.tech account with your twitter) and try it. I bought some twitter account but there is needed verification because i didnt created these accounts myself, trying to update the code right now to use twitter account cookies but cant figure this one out so far. Also this code is still under construction, that mean there are bugs. Also uf you want to use gpt api to generate tweet texts and replies delete tweet_message, reply_message and uncomment the # tweet_message, # reply_message, # openai_api_key

So this is what you need:
1. you need twitter account handle and password of account that is already linked to post.tech
2. create .env
3. you can use as it is but the tweet will be tweet_message = "Hey" and replies     reply_message = "I agree"
or use gpt api

**Comment by pipks** [comment]
Thank you very much for this detailed answer. Can we use GPT to generate automatic replies based on tweet content, or will it use the patterns we specify?

**Comment by Popinek** [comment]
Yes the idea is you set up your persona in gpt.py something like "Im 20 years old cryptotwitter expert, i like memes and ...." the prompt is the topic you going to tweet about, i want to set up a list of topics and randomly choose and let gpt to generate the tweet. With replies we going to read the tweet so gpt can generate relevant answer.
